# Generated by Django 4.2.2 on 2023-06-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Price", models.CharField(max_length=20)),
                ("Details", models.CharField(max_length=20)),
                ("Quantity", models.CharField(max_length=20)),
                ("Image", models.FileField(upload_to="%Y%m%d")),
                (
                    "Admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.admin_tb"
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.category_tb",
                    ),
                ),
            ],
        ),
    ]
