# Generated by Django 4.2.2 on 2023-06-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Admin", "0003_remove_product_tb_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_tb",
            name="Admin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admin.admin_tb",
            ),
        ),
    ]
