# Generated by Django 3.2.5 on 2021-07-24 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer_Tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("Gender", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=300)),
                ("ContactNumber", models.CharField(max_length=30)),
                ("City", models.CharField(max_length=30)),
                ("State", models.CharField(max_length=30)),
                ("Zip", models.PositiveIntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Cart_Tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.CharField(max_length=20)),
                ("Total", models.CharField(max_length=20)),
                (
                    "Date",
                    models.DateTimeField(
                        default=datetime.datetime(2021, 7, 24, 15, 31, 46, 851297)
                    ),
                ),
                ("Status", models.CharField(default="Pending", max_length=20)),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.product_tb",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Buyer.buyer_tb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateTimeField(
                        default=datetime.datetime(2021, 7, 24, 15, 31, 46, 852297)
                    ),
                ),
                ("Method", models.CharField(default="COD", max_length=20)),
                ("Status", models.CharField(default="Pending", max_length=20)),
                ("Quantity", models.CharField(default="", max_length=20)),
                ("Total", models.CharField(default="", max_length=20)),
                (
                    "Cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Buyer.cart_tb"
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Buyer.buyer_tb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Address_Tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateTimeField(
                        default=datetime.datetime(2021, 7, 24, 15, 31, 46, 853296)
                    ),
                ),
                ("Address", models.CharField(max_length=200)),
                ("Pin", models.CharField(max_length=20)),
                ("Mobile", models.CharField(max_length=20)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Buyer.buyer_tb"
                    ),
                ),
            ],
        ),
    ]
