# Generated by Django 3.2.5 on 2021-07-24 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 15, 51, 14, 729659)),
        ),
        migrations.AlterField(
            model_name='order_address_tb',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 15, 51, 14, 730659)),
        ),
        migrations.DeleteModel(
            name='Order_Tb',
        ),
    ]
