# Generated by Django 3.2.5 on 2021-07-24 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Admin", "0001_initial"),
        ("Buyer", "0002_auto_20210724_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_tb",
            name="Date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 7, 24, 15, 51, 55, 960153)
            ),
        ),
        migrations.AlterField(
            model_name="order_address_tb",
            name="Date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 7, 24, 15, 51, 55, 963151)
            ),
        ),
        migrations.CreateModel(
            name="Order_Tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateTimeField(
                        default=datetime.datetime(2021, 7, 24, 15, 51, 55, 962151)
                    ),
                ),
                ("Method", models.CharField(default="COD", max_length=20)),
                ("Status", models.CharField(default="Pending", max_length=20)),
                ("Quantity", models.CharField(max_length=20)),
                ("Total", models.CharField(max_length=20)),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.product_tb",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Buyer.buyer_tb"
                    ),
                ),
            ],
        ),
    ]
