# Generated by Django 4.2.2 on 2023-06-29 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Buyer", "0003_auto_20210724_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_tb",
            name="Date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 29, 16, 57, 44, 822337)
            ),
        ),
        migrations.AlterField(
            model_name="order_tb",
            name="Date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 29, 16, 57, 44, 822337)
            ),
        ),
        migrations.DeleteModel(
            name="Order_Address_Tb",
        ),
    ]
