# Generated by Django 3.2.5 on 2023-06-29 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_alter_cart_tb_date_alter_order_tb_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 21, 9, 658046)),
        ),
        migrations.AlterField(
            model_name='order_tb',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 21, 9, 658046)),
        ),
    ]
