# Generated by Django 4.2.2 on 2023-06-30 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Buyer", "0005_auto_20230629_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_tb",
            name="Date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="order_tb",
            name="Date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
